#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}'

branches:
  only:
  - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

# clone directory
clone_folder: c:\projects\otfft

# set clone depth
clone_depth: 5   

# images
image:
  - Visual Studio 2017
  - Visual Studio 2013

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Release     
      BOOST_ROOT: "C:\\Libraries\\boost_1_65_1"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib64-msvc-14.1"

    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Debug
      BOOST_ROOT: "C:\\Libraries\\boost_1_65_1"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib64-msvc-14.1"

    - GENERATOR: "Visual Studio 12 2013 Win64"
      CONFIG: Release
      BOOST_ROOT: "C:\\Libraries\\boost_1_58_0"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib64-msvc-12.0"

    - GENERATOR: "Visual Studio 12 2013 Win64"
      CONFIG: Debug
      BOOST_ROOT: "C:\\Libraries\\boost_1_58_0"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%\\lib64-msvc-12.0"

matrix:
  exclude:
    - image: Visual Studio 2017
      GENERATOR: "Visual Studio 12 2013 Win64"
    - image: Visual Studio 2013
      GENERATOR: "Visual Studio 15 2017 Win64"

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"

test_script:
  - ps: cd _builds
  - set PATH=%BOOST_LIBRARYDIR%;%PATH%
  - ctest -VV -C "%CONFIG%"
